### ISSUE TITLE
the length of inference lines

### ISSUE THREAD

**Issue by yuishiyumeiji** [quawai/viaLogic#1]
The length of inference lines seems not appropriate (e.g. [resume of class 2, p. 2](https://github.com/quawai/viaLogic/blob/master/class02/resume.pdf), [code](https://github.com/quawai/viaLogic/blob/master/class02/draft.saty#L102)). The inference lines provided by the package [proof.satyh](https://github.com/gfngfn/SATySFi/blob/master/lib-satysfi/dist/packages/proof.satyh) look like fractions.

**Comment by quawai** [comment]
The LaTeX version is added.
